<template>
  <div class="loader">
      <div class="loadingio-spinner-ripple-m0vuu6fa8ag"><div class="ldio-8xku71iz2ei">
<div></div><div></div>
</div></div>
  {{title}}
  </div>
</template>

<script>
export default {
  props: ['title']
}
</script>

<style scoped>
.loader{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 200;
    text-align: center;
    font-size: 14px;
    display: flex;
    flex-direction: column;
    align-items: center;
}
@keyframes ldio-8xku71iz2ei {
  0% {
    top: 48px;
    left: 48px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 9px;
    left: 9px;
    width: 78px;
    height: 78px;
    opacity: 0;
  }
}

.ldio-8xku71iz2ei div {
  position: absolute;
  border-width: 2px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-8xku71iz2ei 1s cubic-bezier(0,0.2,0.8,1) infinite;
}

.ldio-8xku71iz2ei div:nth-child(1) {
  border-color: #0a0a0a
}

.ldio-8xku71iz2ei div:nth-child(2) {
  border-color: #28292f;
  animation-delay: -0.5s;
}

.loadingio-spinner-ripple-m0vuu6fa8ag {
  width: 100px;
  height: 100px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-8xku71iz2ei {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-8xku71iz2ei div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>